env:
  TERM: xterm-256color
colors:
#   # Default colors
   primary:
     background: '#002b36' # base03
#     foreground: '#839496' # base0

#   # Cursor colors
#   cursor:
#     text:   '#002b36' # base03
#     cursor: '#839496' # base0

#   # Normal colors
#   normal:
#     black:   '#073642' # base02
#     red:     '#dc322f' # red
#     green:   '#859900' # green
#     yellow:  '#b58900' # yellow
#     blue:    '#268bd2' # blue
#     magenta: '#d33682' # magenta
#     cyan:    '#2aa198' # cyan
#     white:   '#eee8d5' # base2

  # Bright colors
  # bright:
  #   black:   '#002b36' # base03
  #   red:     '#cb4b16' # orange
  #   green:   '#586e75' # base01
  #   yellow:  '#657b83' # base00
  #   blue:    '#839496' # base0
  #   magenta: '#6c71c4' # violet
  #   cyan:    '#93a1a1' # base1
  #   white:   '#fdf6e3' # base3
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: 'Fira Code'
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic

size: 20.0

offset:
  x: 0
  y: 0
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,       action: IncreaseFontSize }
  - { key: NumpadSubtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
